services:
  # Unified MCP Pool Server
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-pool-server
    # ports:
    #   - "3000:3000"
    environment:
      - PORT=3000
      - CONVEX_URL=${CONVEX_URL:-https://fearless-husky-961.convex.cloud}
      - CONVEX_DEPLOY_KEY=${CONVEX_DEPLOY_KEY:-dev:fearless-husky-961}
      # SSL config
      - VIRTUAL_HOST=mcp.codespeaks.dev
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=mcp.codespeaks.dev
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - .:/app
    networks:
      - mcp-pool
      - reverse-proxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mcp-pool:
    driver: bridge
    name: mcp-pool
  reverse-proxy:
    external: true